import 'package:flutter_bloc/flutter_bloc.dart';
import '../../services/database_service.dart';
import '../../models/it_policy_model.dart';
import 'it_dashboard_state.dart';

class ITDashboardCubit extends Cubit<ITDashboardState> {
  final DatabaseService _databaseService = DatabaseService();

  ITDashboardCubit() : super(ITDashboardInitial());

  Future<void> loadDashboard() async {
    emit(ITDashboardLoading());

    try {
      final results = await Future.wait([
        _databaseService.getITPolicies(),
        _databaseService.getTotalEmployeesCount(),
        // TODO: Add getActiveDevicesCount() to database service
        Future.value(0), // Placeholder for active devices
      ]);

      final policies = results[0] as List;
      final totalUsers = results[1] as int;
      final activeDevices = results[2] as int;

      emit(ITDashboardLoaded(
        policies: policies.cast(),
        totalUsers: totalUsers,
        activeDevices: activeDevices,
      ));
    } catch (e) {
      emit(ITDashboardError(e.toString()));
    }
  }

  Future<void> refresh() async {
    await loadDashboard();
  }
}

class ITPolicyCubit extends Cubit<ITPolicyState> {
  final DatabaseService _databaseService = DatabaseService();

  ITPolicyCubit() : super(ITPolicyInitial());

  Future<void> loadPolicies() async {
    emit(ITPolicyLoading());

    try {
      final policies = await _databaseService.getITPolicies();
      emit(ITPolicyLoaded(policies));
    } catch (e) {
      emit(ITPolicyError(e.toString()));
    }
  }

  Future<void> createPolicy({
    required String title,
    required String description,
    String? policyType,
    String? pdfUrl,
  }) async {
    try {
      final policy = ITPolicyModel(
        id: '', // Will be generated by Supabase
        title: title,
        description: description,
        policyType: policyType,
        pdfUrl: pdfUrl,
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );
      await _databaseService.createITPolicy(policy);
      emit(const ITPolicySuccess('Policy created successfully'));
      await loadPolicies();
    } catch (e) {
      emit(ITPolicyError(e.toString()));
    }
  }

  Future<void> updatePolicy({
    required String id,
    required String title,
    required String description,
    String? policyType,
    String? pdfUrl,
  }) async {
    try {
      final policy = ITPolicyModel(
        id: id,
        title: title,
        description: description,
        policyType: policyType,
        pdfUrl: pdfUrl,
        isActive: true,
        createdAt: DateTime.now(), // Will be preserved by DB
        updatedAt: DateTime.now(),
      );
      await _databaseService.updateITPolicy(policy);
      emit(const ITPolicySuccess('Policy updated successfully'));
      await loadPolicies();
    } catch (e) {
      emit(ITPolicyError(e.toString()));
    }
  }

  Future<void> deletePolicy(String id) async {
    try {
      await _databaseService.deleteITPolicy(id);
      emit(const ITPolicySuccess('Policy deleted successfully'));
      await loadPolicies();
    } catch (e) {
      emit(ITPolicyError(e.toString()));
    }
  }
}
